#pragma once
void drawWord(const char word[], int wordSize, int x, int y, int size);
void drawFont(int x, int y, const unsigned char sprite[], int size);
extern const unsigned char letterB[75];
extern const unsigned char letterJ[75];
extern const unsigned char letterK[75];
extern const unsigned char letterW[75];
extern const unsigned char letterX[75];
extern const unsigned char letterG[75];
extern const unsigned char letterF[75];
extern const unsigned char letterY[75];
extern const unsigned char letterC[75];
extern const unsigned char letterT[75];
extern const unsigned char letterH[75];
extern const unsigned char letterO[75];
extern const unsigned char letterS[75];
extern const unsigned char letterA[75];
extern const unsigned char letterM[75];
extern const unsigned char letterU[75];
extern const unsigned char letterN[75];
extern const unsigned char letterE[75];
extern const unsigned char letterI[75];
extern const unsigned char letterZ[75];
extern const unsigned char letterP[75];
extern const unsigned char letterD[75];
extern const unsigned char letterL[75];
extern const unsigned char letterV[75];
extern const unsigned char letterR[75];
extern const unsigned char letterQ[75];